#Convention: Order the require_relative statements in alphabetical order
require_relative 'auth'
require_relative 'contact'
require_relative 'dashboards'
require_relative 'filters'
require_relative 'master_locationstructure'
require_relative 'master_partinfo'
require_relative 'part'
require_relative 'personnel'
require_relative 'service'
require_relative 'store'
require_relative 'tickets'
require_relative 'uom'
require_relative 'usermgt'
